- name: "bugfix"
  color: "d73a4a"
  description: "Bugfix"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "ci-cd"
  color: "0075ca"
  description: "Improvements or additions to CD/CD"
- name: "tests"
  color: "0075ca"
  description: "Improvements or additions to tests"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
- name: "wontfix_it"
  color: "000000"
  description: "This will not be worked on"
  from_name: "wontfix"
