name: Handle PRs to main branch

on:
  pull_request:
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Labeler
      if: success()
      uses: crazy-max/ghaction-github-labeler@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        yaml-file: .github/labels.yaml
        skip-delete: false
        dry-run: false
        exclude: |
          help*
          *issue
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: prepare env for testing
      run: make prepare
    - name: run stylecheck
      run: make black
    - name: run tests
      run: make unittest
